### ISSUE TITLE
sql or mongodb docker image

### ISSUE THREAD

**Issue by domzgarcia** [LordDashMe/knowledge#4]
in devops, what about images for databases? how to create one

**Comment by LordDashMe** [comment]
Hi, there! I actually don't create a separate image related to DB anymore, and I suggest using the official images from docker hub  ex. [mysql](https://hub.docker.com/_/mysql) with docker compose is the best way which is also recommended by the docker community. What's lacking in the docker folder are the examples how to implement it with docker compose. Here's the quick example how I done it with docker compose.

```yml
version: '3.4'

services:

  my-node-app:
    tty: true
    stdin_open: true
    image: 'node:10-alpine'
    volumes:
      - '${DOCKER_HOST_SOURCE_PATH}:/var/www/site/'

  mongodb-3.4.10:
    image: 'mongo:3.4.10'
    volumes:
      - '${DOCKER_HOST_MONGO_DB_SOURCE_PATH}:/data/db/'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${DOCKER_MONGO_INITDB_ROOT_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DOCKER_MONGO_INITDB_ROOT_PASSWORD}'

networks:
  default:
    external:
      name: '${DOCKER_HOST_PRE_DEFINED_NETWORK}'
```

If you have more questions don't hesitate to email me, we can discuss further. Also if you have found any inaccurate content in our folders feel free to create a pull request for it. Thanks! :-)
